# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Different in a good way.
email: paragasu@gmail.com
description: Different in a good way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paragasu.github.io" # the base hostname & protocol for your site
twitter_username: paragasu
github_username:  paragasu
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown

destination: /home/paragasu/Workspace/paragasu.github.io
